version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - forecast

  auth:
    build: ./auth
    ports:
      - "3001:3001"

  forecast:
    build: ./weather
    ports:
      - "3002:3002"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
